### ISSUE TITLE
The Roadmap

### ISSUE THREAD

**Issue by ghost** [MetaMask/eth-ipld-hot-importer#2]
_Yet another roadmap..._

Moving from https://github.com/MetaMask/eth-ipfs-browser-client/issues/1

## Ethereum Browser Light Client Roadmap (MVP)

Divided in **five** big areas

* Obtaining Data from _devp2p_
* Kitsunet: metamask peer network
* Bridge Peers: Make eth contain available to libp2p
* Browser Peers Why we are here
* Metamask Extension Ops

### OBTAINING DATA FROM devp2p
  
- [x] Devp2p Node Scrapper
- [x] Block Header Sync
- [ ] Client Fork (to add trie nodes to RedisDB)
- [ ] Snapshot download (from devp2p)

### KITSUNET (Metamask peer network)

- [x] Add mustekala box mk1 docker to repo
  - [x] Deploy
- [ ] Signalling servers
  - [ ] Docker package
  - [ ] Deploy
  - [ ] Network bootstrapping
- [ ] PubSub Testing for blockchain head update
  - [ ] May include signature of messages / "network of trust" ?
- [ ] Messaging testing
  - [ ] Request an "index"
- [ ] Metrics
  - [ ] Collection

### BRIDGE (Make eth content available to libp2p)

(go-ipfs)

- [ ] **Mount RedisDB Datastore** problem
- [ ] Bootstrap into kitsunetto
- [ ] Custom **Content Routing System**
  - [ ] Sharding criteria, metadata indexes, "delta computations", etc
- [ ] **Publish** new blockchain head
- [ ] Respond to **requests**
  - [ ] eth - ipld dag requests
  - [ ] CRS indexes requests

### PEERS
	
(js-ipfs)

- [ ] Bootstrap into kitsunetto
- [ ] **Subscribe** to new blockchain head
- [ ] Custom **Content Routing System**
  - [ ] Maintaining **Ethereum Trie Shards**
    - [ ] Deterministic and/or discrete
    - [ ] Incentive system
    - [ ] Updating them on triggers, request indexes, compute deltas, request parts.
- [ ] Manage other peers **requests**
  - [ ] eth - ipld dag requests
  - [ ] CRS indexes requests

### Metamask Extension Ops

- [ ] eth_blockNumber
- [ ] eth_getBalance
- [ ] **... more to come.** (See breakdown in comment below)

**Comment by ghost** [comment]
break down of rpc methods and node requirements (updated)
```
client
  eth_protocolVersion
  eth_syncing
  eth_coinbase
  eth_mining
  eth_hashrate
  eth_gasPrice
  eth_accounts
  eth_sign
  eth_sendTransaction
  eth_sendRawTransaction
  eth_newFilter
  eth_newBlockFilter
  eth_newPendingTransactionFilter
  eth_uninstallFilter
  eth_getFilterChanges
  eth_getFilterLogs

client broadcast
  eth_sendRawTransaction

ipfs
  eth_getBlockByHash
  eth_getUncleByBlockHashAndIndex

ipns/block syncing (head tracking)
  eth_blockNumber

ipld:selectors (selectors/transforms)
  eth_getBlockTransactionCountByHash
  eth_getUncleCountByBlockHash

index:txToBlock (coselector)
  eth_getTransactionReceipt
  eth_getTransactionByHash
  eth_getTransactionByBlockHashAndIndex

log query?? / geth bloomFilterTrie / index:logToTx
  eth_getLogs (+index:logToTx)

lazy vm (slow) / remote vm + proofs (faster)
  eth_call
  eth_estimateGas

index:CHT
  eth_call
  eth_estimateGas
  eth_getBalance
  eth_getStorageAt
  eth_getTransactionCount
  eth_getCode
  eth_getBlockByNumber
  eth_getTransactionByBlockNumberAndIndex (+index:txToBlock)
  eth_getBlockTransactionCountByNumber (+ipld:selectors)
  eth_getUncleCountByBlockNumber (+ipld:selectors)
  eth_getUncleByBlockNumberAndIndex
  eth_getLogs (+log query)
```
